icons_format = " "

[[block]]
block = "net"
device = "wg0"
format = "wg0"
hide_inactive = true

[[block]]
block = "net"
device = "br0"
format = "br0({ip})"
hide_inactive = true

[[block]]
block = "net"
device = "eth0"
format = "eth0({ip})"
hide_inactive = true

[[block]]
block = "net"
device = "wlan0"
format = "wlan0({ip})"
format_alt = "wlan0({ssid};{signal_strength};{ip})"
hide_inactive = true

[[block]]
block = "cpu"
format = "c{utilization:0}"

[[block]]
block = "memory"
format_mem = "m{mem_used_percents:1}"
on_click = "" # don't show swap

[[block]]
block = "temperature"
collapsed = false
chip = "k10temp-pci-00c3"
format = "{average:1}"
on_click = "" # don't collapse

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "backlight"

[[block]]
block = "custom"
interval = 1
command = "</sys/class/power_supply/AC/online"
hide_when_empty = true

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
full_format = "{percentage}"
hide_missing = true

[[block]]
block = "custom"
command = '''python3 -c 'import dateutil.relativedelta as r;from datetime import datetime as d;x=r.relativedelta(d.fromtimestamp(1652443200), d.now()); print(f"{x.days}d{x.hours}h")''''

[[block]]
block = "custom"
command = '''python3 -c 'import dateutil.relativedelta as r;from datetime import datetime as d;x=r.relativedelta(d.fromtimestamp(1653127200), d.now()); print(f"{x.days}d{x.hours}h")''''

[[block]]
block = "time"
interval = 1
format = "%Y-%m-%d %H:%M:%S"
