icons_format = " "

[[block]]
block = "net"
device = "wg0"
format = "wg0"
hide_inactive = true

[[block]]
block = "net"
device = "br0"
format = "br0({ip})"
hide_inactive = true

[[block]]
block = "net"
device = "eth0"
format = "eth0({ip})"
hide_inactive = true

[[block]]
block = "net"
device = "wlan0"
format = "wlan0({ip})"
format_alt = "wlan0({ssid};{signal_strength};{ip})"
hide_inactive = true

[[block]]
block = "cpu"
format = "c{utilization:0}"

[[block]]
block = "memory"
format_mem = "m{mem_used_percents:1}"
on_click = "" # don't show swap

[[block]]
block = "temperature"
collapsed = false
chip = "k10temp-pci-00c3"
format = "{average:1}"
on_click = "" # don't collapse

[[block]]
block = "sound"
format = "{output_name} {volume}"
step_width = 5
show_volume_when_muted = true
on_click = "pavucontrol"
[block.mappings]
"alsa_output.pci-0000_07_00.6.analog-stereo" = "speaker"
"alsa_output.pci-0000_01_00.1.hdmi-stereo-extra3" = "monitor"

[[block]]
block = "backlight"

[[block]]
block = "custom"
interval = 1
command = "</sys/class/power_supply/AC/online"
hide_when_empty = true

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
full_format = "{percentage}"
hide_missing = true

[[block]]
block = "time"
interval = 1
format = "%Y-%m-%d %H:%M:%S"
