add_newline = true
format = """
$username\
$hostname\
$directory\

$git_branch\
$git_commit\
$git_state\
$git_status\

$python\

$character"""

[username]
format = "[$user]($style)@"

[hostname]
format = "[$hostname]($style) "

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 3

[git_status]
format = "$ahead_behind$conflicted$stashed$deleted$renamed$staged$modified$untracked"
ahead = "[⇡${count}](yellow) "
behind = "[⇣${count}](yellow) "
stashed = "[*${count}](yellow) "
deleted = "[x${count}](red) "
staged = "[+${count}](yellow) "
modified = "[!${count}](yellow) "
untracked = "[?${count}](cyan) "

[python]
format = 'with [${symbol}${pyenv_prefix}($virtualenv )]($style)'
detect_files = []
detect_extensions = []
