icons_format = " "

[icons]
icons = "awesome6"

[theme.overrides]
separator = ""
critical_bg = "#ff0055"
critical_fg = "#000000"
warning_bg = "#ff0055"
warning_fg = "#000000"
#good_fg = "#ff0055"
#idle_fg = "#ff0055"
#info_fg = "#ff0055"

[[block]]
block = "net"
device = "wg0"
format = " wg0 "
missing_format = ""

[[block]]
block = "net"
device = "br0"
format = " br0({$ip|no ip}) "
inactive_format = " br0(down) "
missing_format = ""

[[block]]
block = "net"
device = "eth0"
format = " eth0({$ip|no ip}) "
inactive_format = " eth0(down) "
missing_format = ""

[[block]]
block = "net"
device = "usb0"
format = " usb0({$ip|no ip}) "
inactive_format = " usb0(down) "
missing_format = ""

[[block]]
block = "net"
device = "wlan0"
format = " wlan0({$ip|no ip}) "
format_alt = " wlan0($ssid;$signal_strength;{$ip|no ip}) "
inactive_format = " wlan0(down) "
missing_format = ""

[[block]]
block = "cpu"
format = " c$utilization.eng(width:2) "

[[block]]
block = "memory"
format = " m$mem_used_percents.eng(width:2) "

[[block]]
if_command = "[ $(hostname) = toshiro ]"
block = "temperature"
chip = "k10temp-pci-00c3"
format = " $average "

[[block]]
if_command = "[ $(hostname) = katsumi ]"
block = "temperature"
chip = "coretemp-isa-0000"
format = " $average "

[[block]]
block = "sound"
format = " $output_name($volume) | launching pipewire... "
step_width = 5
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.mappings]
# toshiro
"alsa_output.pci-0000_07_00.6.analog-stereo" = "speaker"
"alsa_output.pci-0000_07_00.6.HiFi__hw_Generic_1__sink" = "built-in"
"alsa_output.pci-0000_01_00.1.hdmi-stereo-.*" = "monitor"
# katsumi
"alsa_output.pci-0000_0a_00.4.analog-stereo" = "line out"
"alsa_output.pci-0000_00_1f.3.analog-stereo" = "speaker"
"alsa_output.pci-0000_08_00.1.hdmi-stereo" = "hdmi"
# other
"alsa_output.usb-Plantronics.*" = "headset"
"alsa_output.usb-Apple__Inc.*" = "dongle"

[[block]]
if_command = "[ $(hostname) = toshiro ]"
block = "backlight"
format = " $brightness "

[[block]]
block = "custom"
interval = 1
command = "</sys/class/power_supply/AC/online"
format = " $text "
hide_when_empty = true

[[block]]
if_command = "[ -d /sys/class/power_supply/BAT0 ]"
block = "battery"
interval = 10
format = " $percentage "
full_format = " $percentage "
missing_format = ""

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%Y-%m-%d %H:%M:%S') "
